version: "3.9"
services:
  service:
    image: webprint/service:latest
    restart: always
    build: ..
    environment:
      - WEBPRINT_SERVER_ENDPOINT=${WEBPRINT_SERVER_ENDPOINT}
      - WEBPRINT_SERVICE_KEY=${WEBPRINT_SERVICE_KEY}
      - CUPS_SERVER=cups:631
    volumes:
      - ./debug-output:/tmp/webprint-service-debug-output
    depends_on:
      - cups
    links:
      - cups

  cups:
    image: ydkn/cups:latest
    restart: always
    volumes:
      - ./cups:/etc/cups
    environment:
      - ADMIN_PASSWORD=${CUPS_ADMIN_PASSWORD}
    expose:
      - 631
    ports:
      - "6310:631"
#    profiles:
#      - debug
